# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lmn_2_qgis_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LMN_to_QGISDialogBase(object):
    def setupUi(self, LMN_to_QGISDialogBase):
        LMN_to_QGISDialogBase.setObjectName("LMN_to_QGISDialogBase")
        LMN_to_QGISDialogBase.resize(767, 289)
        LMN_to_QGISDialogBase.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(LMN_to_QGISDialogBase)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 1, 1, 1)
        self.pbBrowseSLMN = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbBrowseSLMN.setToolTipDuration(7)
        self.pbBrowseSLMN.setObjectName("pbBrowseSLMN")
        self.gridLayout_4.addWidget(self.pbBrowseSLMN, 3, 2, 1, 1)
        self.pbLoad = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbLoad.setMaximumSize(QtCore.QSize(16777215, 1800))
        self.pbLoad.setObjectName("pbLoad")
        self.gridLayout_4.addWidget(self.pbLoad, 8, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.leUNL = QtWidgets.QLineEdit(LMN_to_QGISDialogBase)
        self.leUNL.setObjectName("leUNL")
        self.gridLayout_4.addWidget(self.leUNL, 1, 1, 1, 1)
        self.pbBrowseUNL = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbBrowseUNL.setObjectName("pbBrowseUNL")
        self.gridLayout_4.addWidget(self.pbBrowseUNL, 1, 2, 1, 1)
        self.lePOCH = QtWidgets.QLineEdit(LMN_to_QGISDialogBase)
        self.lePOCH.setObjectName("lePOCH")
        self.gridLayout_4.addWidget(self.lePOCH, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 6, 1, 1, 1)
        self.pbBrowseKSLMN = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbBrowseKSLMN.setObjectName("pbBrowseKSLMN")
        self.gridLayout_4.addWidget(self.pbBrowseKSLMN, 7, 2, 1, 1)
        self.pbCancel = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbCancel.setObjectName("pbCancel")
        self.gridLayout_4.addWidget(self.pbCancel, 9, 2, 1, 1)
        self.label = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 1, 1, 1)
        self.leKSLMN = QtWidgets.QLineEdit(LMN_to_QGISDialogBase)
        self.leKSLMN.setObjectName("leKSLMN")
        self.gridLayout_4.addWidget(self.leKSLMN, 7, 1, 1, 1)
        self.pbClear = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbClear.setObjectName("pbClear")
        self.gridLayout_4.addWidget(self.pbClear, 8, 2, 1, 1)
        self.leSLMN = QtWidgets.QLineEdit(LMN_to_QGISDialogBase)
        self.leSLMN.setObjectName("leSLMN")
        self.gridLayout_4.addWidget(self.leSLMN, 3, 1, 1, 1)
        self.pbBrowsePOCH = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbBrowsePOCH.setObjectName("pbBrowsePOCH")
        self.gridLayout_4.addWidget(self.pbBrowsePOCH, 5, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.stonerHobbit = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stonerHobbit.sizePolicy().hasHeightForWidth())
        self.stonerHobbit.setSizePolicy(sizePolicy)
        self.stonerHobbit.setMinimumSize(QtCore.QSize(0, 0))
        self.stonerHobbit.setMaximumSize(QtCore.QSize(185, 245))
        self.stonerHobbit.setText("")
        self.stonerHobbit.setPixmap(QtGui.QPixmap(":/plugins/lmn_2_qgis/icon.svg"))
        self.stonerHobbit.setScaledContents(True)
        self.stonerHobbit.setAlignment(QtCore.Qt.AlignCenter)
        self.stonerHobbit.setIndent(-1)
        self.stonerHobbit.setObjectName("stonerHobbit")
        self.gridLayout.addWidget(self.stonerHobbit, 0, 0, 1, 1)
        self.action_Open = QtWidgets.QAction(LMN_to_QGISDialogBase)
        self.action_Open.setObjectName("action_Open")

        self.retranslateUi(LMN_to_QGISDialogBase)
        QtCore.QMetaObject.connectSlotsByName(LMN_to_QGISDialogBase)

    def retranslateUi(self, LMN_to_QGISDialogBase):
        _translate = QtCore.QCoreApplication.translate
        LMN_to_QGISDialogBase.setWindowTitle(_translate("LMN_to_QGISDialogBase", "LMN to QGIS"))
        self.label_3.setText(_translate("LMN_to_QGISDialogBase", "(Opcjonalnie) Wskaż plik ZIP zawierający warstwy pochodne"))
        self.pbBrowseSLMN.setText(_translate("LMN_to_QGISDialogBase", "Przeglądaj"))
        self.pbLoad.setText(_translate("LMN_to_QGISDialogBase", "Wczytaj dane"))
        self.label_2.setText(_translate("LMN_to_QGISDialogBase", "Wskaż plik ZIP zawierający pliki UNL"))
        self.pbBrowseUNL.setText(_translate("LMN_to_QGISDialogBase", "Przeglądaj"))
        self.label_4.setText(_translate("LMN_to_QGISDialogBase", "(Opcjonalnie) Wskaż plik ZIP zawierający warstwy \"Kontrole SLMN\""))
        self.pbBrowseKSLMN.setText(_translate("LMN_to_QGISDialogBase", "Przeglądaj"))
        self.pbCancel.setText(_translate("LMN_to_QGISDialogBase", "Anuluj"))
        self.label.setText(_translate("LMN_to_QGISDialogBase", "Wskaż plik ZIP zawierający warstwy SLMN"))
        self.pbClear.setText(_translate("LMN_to_QGISDialogBase", "Wyczyść"))
        self.pbBrowsePOCH.setText(_translate("LMN_to_QGISDialogBase", "Przeglądaj"))
        self.action_Open.setText(_translate("LMN_to_QGISDialogBase", "&Open..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LMN_to_QGISDialogBase = QtWidgets.QDialog()
    ui = Ui_LMN_to_QGISDialogBase()
    ui.setupUi(LMN_to_QGISDialogBase)
    LMN_to_QGISDialogBase.show()
    sys.exit(app.exec_())
