# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lmn_2_qgis_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LMN_to_QGISDialogBase(object):
    def setupUi(self, LMN_to_QGISDialogBase):
        LMN_to_QGISDialogBase.setObjectName("LMN_to_QGISDialogBase")
        LMN_to_QGISDialogBase.resize(485, 305)
        LMN_to_QGISDialogBase.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(LMN_to_QGISDialogBase)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.leSLMN = QtWidgets.QLineEdit(LMN_to_QGISDialogBase)
        self.leSLMN.setObjectName("leSLMN")
        self.gridLayout.addWidget(self.leSLMN, 9, 0, 1, 2)
        self.pbBrowseKSLMN = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbBrowseKSLMN.setObjectName("pbBrowseKSLMN")
        self.gridLayout.addWidget(self.pbBrowseKSLMN, 14, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 2)
        self.pbLoad = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbLoad.setMaximumSize(QtCore.QSize(16777215, 1800))
        self.pbLoad.setObjectName("pbLoad")
        self.gridLayout.addWidget(self.pbLoad, 16, 0, 2, 1)
        self.pbCancel = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbCancel.setObjectName("pbCancel")
        self.gridLayout.addWidget(self.pbCancel, 17, 1, 1, 2)
        self.lePOCH = QtWidgets.QLineEdit(LMN_to_QGISDialogBase)
        self.lePOCH.setObjectName("lePOCH")
        self.gridLayout.addWidget(self.lePOCH, 12, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 13, 0, 1, 1)
        self.leKSLMN = QtWidgets.QLineEdit(LMN_to_QGISDialogBase)
        self.leKSLMN.setObjectName("leKSLMN")
        self.gridLayout.addWidget(self.leKSLMN, 14, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 15, 0, 1, 1)
        self.pbVacuum = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbVacuum.setObjectName("pbVacuum")
        self.gridLayout.addWidget(self.pbVacuum, 16, 1, 1, 2)
        self.label = QtWidgets.QLabel(LMN_to_QGISDialogBase)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.leUNL = QtWidgets.QLineEdit(LMN_to_QGISDialogBase)
        self.leUNL.setObjectName("leUNL")
        self.gridLayout.addWidget(self.leUNL, 6, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 18, 0, 1, 1)
        self.pbBrowseUNL = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbBrowseUNL.setObjectName("pbBrowseUNL")
        self.gridLayout.addWidget(self.pbBrowseUNL, 6, 2, 1, 1)
        self.pbBrowsePOCH = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbBrowsePOCH.setObjectName("pbBrowsePOCH")
        self.gridLayout.addWidget(self.pbBrowsePOCH, 12, 2, 1, 1)
        self.pbBrowseSLMN = QtWidgets.QPushButton(LMN_to_QGISDialogBase)
        self.pbBrowseSLMN.setToolTipDuration(7)
        self.pbBrowseSLMN.setObjectName("pbBrowseSLMN")
        self.gridLayout.addWidget(self.pbBrowseSLMN, 9, 2, 1, 1)
        self.action_Open = QtWidgets.QAction(LMN_to_QGISDialogBase)
        self.action_Open.setObjectName("action_Open")

        self.retranslateUi(LMN_to_QGISDialogBase)
        QtCore.QMetaObject.connectSlotsByName(LMN_to_QGISDialogBase)

    def retranslateUi(self, LMN_to_QGISDialogBase):
        _translate = QtCore.QCoreApplication.translate
        LMN_to_QGISDialogBase.setWindowTitle(_translate("LMN_to_QGISDialogBase", "LMN to QGIS"))
        self.pbBrowseKSLMN.setText(_translate("LMN_to_QGISDialogBase", "Przeglądaj"))
        self.label_2.setText(_translate("LMN_to_QGISDialogBase", "Wskaż plik ZIP zawierający pliki UNL"))
        self.pbLoad.setText(_translate("LMN_to_QGISDialogBase", "Wczytaj dane"))
        self.pbCancel.setText(_translate("LMN_to_QGISDialogBase", "Anuluj"))
        self.label_3.setText(_translate("LMN_to_QGISDialogBase", "(Opcjonalnie) Wskaż plik ZIP zawierający warstwy pochodne"))
        self.label_4.setText(_translate("LMN_to_QGISDialogBase", "(Opcjonalnie) Wskaż plik ZIP zawierający warstwy \"Kontrole SLMN\""))
        self.pbVacuum.setText(_translate("LMN_to_QGISDialogBase", "Wyczyść"))
        self.label.setText(_translate("LMN_to_QGISDialogBase", "Wskaż plik ZIP zawierający warstwy SLMN"))
        self.pbBrowseUNL.setText(_translate("LMN_to_QGISDialogBase", "Przeglądaj"))
        self.pbBrowsePOCH.setText(_translate("LMN_to_QGISDialogBase", "Przeglądaj"))
        self.pbBrowseSLMN.setText(_translate("LMN_to_QGISDialogBase", "Przeglądaj"))
        self.action_Open.setText(_translate("LMN_to_QGISDialogBase", "&Open..."))
